name: q-galore
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py38h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_1
  - pillow=10.3.0=py38h5eee18b_0
  - pip=24.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - pytorch=2.3.0=py3.8_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py38h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_1
  - setuptools=69.5.1=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.0=py38_cu121
  - torchtriton=2.3.0=py38
  - torchvision=0.18.0=py38_cu121
  - typing_extensions=4.9.0=py38h06a4308_1
  - urllib3=2.1.0=py38h06a4308_1
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.30.0
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - bitsandbytes==0.43.1
      - blessed==1.20.0
      - cachetools==5.3.3
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==2.19.1
      - deepspeed==0.14.2
      - dill==0.3.8
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - email-validator==2.1.1
      - eval-type-backport==0.2.0
      - evaluate==0.4.2
      - exceptiongroup==1.2.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - ffmpy==0.3.2
      - filelock==3.14.0
      - fire==0.6.0
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - galore-torch==1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gpustat==1.1.1
      - gputil==1.4.0
      - gradio==4.31.4
      - gradio-client==0.16.4
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - importlib-resources==6.4.0
      - jieba==0.42.1
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lion-pytorch==0.1.4
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - multidict==6.0.5
      - multiprocess==0.70.16
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nvidia-ml-py==12.535.161
      - nvitop==1.3.2
      - orjson==3.10.3
      - packaging==24.0
      - pandas==2.0.3
      - peft==0.10.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.1
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==16.0.0
      - pyarrow-hotfix==0.6
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydub==0.25.1
      - pygments==2.18.0
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - referencing==0.35.1
      - regex==2024.4.28
      - rich==13.7.1
      - rouge-chinese==1.0.3
      - rpds-py==0.18.1
      - ruff==0.4.4
      - safetensors==0.4.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.1.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sse-starlette==2.1.0
      - starlette==0.37.2
      - style==1.1.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.66.4
      - transformers==4.41.0
      - trl==0.8.1
      - typer==0.12.3
      - tyro==0.8.4
      - tzdata==2024.1
      - ujson==5.10.0
      - update==0.0.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - wandb==0.17.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - websockets==11.0.3
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.18.1